### ISSUE TITLE
In osload "sleep 5" too short

### ISSUE THREAD

**Issue by voerman** [Kramden/Endless#1]
Recent attempts to run the osload script have resulted in frequent failures to load anydesk. Problem was traced to the internet connection not coming online before the command to load anydesk was issued.  The script would hang on the anydesk load and eventually time out. Rerunning the script would just repeat the problem. This seems to be a function of the of the load on the internet connection for Kramden. 

After experimentation, changing the "sleep 5"  to "sleep 15" on line 32 of the osload script seems to fix the problem at the minor expense of making the script take longer to run.

Lou

**Comment by kenvandine** [comment]
Thanks, I'll get that fixed

**Comment by kenvandine** [comment]
Fixed!

**Comment by voerman** [comment]
Thanks Ken, I have updated all known USB sticks at Kramden as of yesterday so no need to redo anything there.
Lou
    On Tuesday, April 23, 2019, 7:30:10 AM PDT, Ken VanDine <notifications@github.com> wrote:  
 
 
Closed #1.
